---
new_page_extension: md
auto_deploy: false
admin_path: "@"
webhook_url: 
sections:
- type: heading
  label: Разделы сайта
- type: directory
  path: _persons
  label: Люди
  create: all
  match: "**/*"
  templates:
  - 27bf13c1-72a1-4238-aec9-8f256e6e156e
- type: directory
  path: _test
  label: test
  create: all
  match: "**/*"
  templates:
  - test
upload_dir: images/persons
public_path: "/images/persons"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
