---
new_page_extension: md
auto_deploy: false
admin_path: "@"
webhook_url: 
collections:
- path: _posts
  label: Posts
  create: all
- path: _persons
  label: Persons
  create: all
- path: ''
  label: Pages
  create: all
upload_dir: images/persons
public_path: "/images/persons"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
