---
new_page_extension: md
auto_deploy: false
admin_path: "@"
webhook_url: 
sections:
- type: heading
  label: Разделы сайта
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _persons
  label: Persons
  create: all
  match: "**/*"
upload_dir: images/persons
public_path: "/images/persons"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
